name: Publish to GitHub Pages

on:
  workflow_dispatch:

jobs:
  update-docs:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository on source branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.ref }} # checkout the branch that triggered the workflow on newest commit

      - name: Checkout repository on documentation branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: build/dokka/generated
          ref: gh-pages

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build documentation
        run: ./gradlew dokkaHtml

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: build/dokka/generated

      - name: Commit documentation
        run: |
          git remote set-url origin https://${{ secrets.SERVICE_ACCOUNT_TOKEN }}@github.com/${{ github.repository }}.git/
          git add .
          git commit -m ":memo: Update version"
          git push
        working-directory: build/dokka/generated